/*
 * My Little Pony
 * Friendship is magic
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Color
 */
public class ColorTest {
    /**
     * Model tests for Color
     */
    @Test
    public void testColor() {
        // TODO: test Color
    }

}
