/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Pony;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-06T23:24:41.937754549+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "ponies", description = "the ponies API")
public interface PoniesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /ponies : List
     *
     * @param name  (optional)
     * @return Status 200 (status code 200)
     *         or Status 400 (status code 400)
     */
    @Operation(
        operationId = "callList",
        summary = "List",
        responses = {
            @ApiResponse(responseCode = "200", description = "Status 200", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Pony.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Status 400")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/ponies",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Pony>> callList(
        @Parameter(name = "name", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"Color\" : \"RED\", \"CreatedAt\" : 0, \"Id\" : \"Id\", \"Name\" : \"Big McIntosh\" }, { \"Color\" : \"RED\", \"CreatedAt\" : 0, \"Id\" : \"Id\", \"Name\" : \"Big McIntosh\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /ponies : Create
     *
     * @param pony  (optional)
     * @return Status 201 (status code 201)
     *         or Status 400 (status code 400)
     */
    @Operation(
        operationId = "create",
        summary = "Create",
        responses = {
            @ApiResponse(responseCode = "201", description = "Status 201", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pony.class))
            }),
            @ApiResponse(responseCode = "400", description = "Status 400")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/ponies",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Pony> create(
        @Parameter(name = "Pony", description = "") @Valid @RequestBody(required = false) Pony pony
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"Color\" : \"RED\", \"CreatedAt\" : 0, \"Id\" : \"Id\", \"Name\" : \"Big McIntosh\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /ponies/{ponyId} : Delete one
     *
     * @param ponyId  (required)
     * @return Status 200 (status code 200)
     */
    @Operation(
        operationId = "deleteOne",
        summary = "Delete one",
        responses = {
            @ApiResponse(responseCode = "200", description = "Status 200")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/ponies/{ponyId}"
    )
    
    default ResponseEntity<Void> deleteOne(
        @Parameter(name = "ponyId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("ponyId") String ponyId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /ponies/{ponyId} : Get one
     *
     * @param ponyId  (required)
     * @return Status 200 (status code 200)
     */
    @Operation(
        operationId = "getOne",
        summary = "Get one",
        responses = {
            @ApiResponse(responseCode = "200", description = "Status 200", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pony.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/ponies/{ponyId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Pony> getOne(
        @Parameter(name = "ponyId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("ponyId") String ponyId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"Color\" : \"RED\", \"CreatedAt\" : 0, \"Id\" : \"Id\", \"Name\" : \"Big McIntosh\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /ponies/{ponyId} : Update
     *
     * @param ponyId  (required)
     * @param pony  (optional)
     * @return Status 200 (status code 200)
     */
    @Operation(
        operationId = "update",
        summary = "Update",
        responses = {
            @ApiResponse(responseCode = "200", description = "Status 200", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pony.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/ponies/{ponyId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Pony> update(
        @Parameter(name = "ponyId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("ponyId") String ponyId,
        @Parameter(name = "Pony", description = "") @Valid @RequestBody(required = false) Pony pony
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"Color\" : \"RED\", \"CreatedAt\" : 0, \"Id\" : \"Id\", \"Name\" : \"Big McIntosh\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
