package bzh.zomzog.prez.contract_first.controller.v2.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@JsonIgnoreProperties(
        value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = CatDto.class, name = "CAT"),
        @JsonSubTypes.Type(value = DogDto.class, name = "DOG")
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public abstract class PetDto {
    private Long id;
    private String name;
    private PetType type;
}
